import pandas as pd

def create_features(input_file, output_file):
    df = pd.read_csv(input_file)
    
    # Create rolling averages for each metric
    metrics = ['metric1', 'metric2', 'metric3', 'metric4', 'metric5', 'metric6', 'metric7', 'metric8', 'metric9']
    for metric in metrics:
        df[f'{metric}_avg'] = df[metric].rolling(window=3).mean()
        df[f'{metric}_diff'] = df[metric].diff()
    
    # Drop rows with NaN values generated by rolling
    df.dropna(inplace=True)

    # Save the features to a new file
    df.to_csv(output_file, index=False)

if __name__ == "__main__":
    create_features('data/processed/equipment_data_processed.csv', 'data/processed/equipment_data_features.csv')
